version: '3.8'

services:
  #SERVICIO DE PERSISTENCIA: PostgreSQL 16
  #Provee la base de datos relacional para el almacenamiento de usuarios, menús y reservas
  db:
    image: postgres:16
    container_name: base_datos_restaurante
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: reservas_db
      
    ports:
      - "5432:5432"
    volumes:
      - base_datos_nueva:/var/lib/postgresql/data
    networks:
      - restaurante_net

  #SERVICIO DE IDENTIDAD: Keycloak
  #Actúa como el proveedor de identidad externo para la gestión de JWT y roles
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: auth_restaurante
    command: start-dev --import-realm # <-- Agregamos esto para que importe el JSON
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak_data:/opt/keycloak/data # Carpeta local para la base de datos interna
      - ./keycloak_import:/opt/keycloak/data/import # Carpeta para el archivo JSON
    networks:
      - restaurante_net

  #SERVICIO DE CACHÉ: Redis
  #Almacenamiento en memoria para acelerar respuestas frecuentes de la API
  redis:
    image: redis:latest
    container_name: cache_restaurante
    ports:
      - "6379:6379"
    networks:
      - restaurante_net

  #SERVICIO DE LÓGICA DE NEGOCIO: API REST (.NET 9)
  #Aplicación principal que integra la base de datos y el servicio de autenticación
  api:
    build:
      context: ./RestauranteApi 
      dockerfile: Dockerfile
    #container_name: api_restaurante
    deploy:
      replicas: 3
    #ports:
      #- "5085:8080" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseEngine=Mongo
      - ConnectionStrings__MongoConnection=mongodb://mongo-router:27017
      #Configuración de conexión utilizando el DNS interno de Docker (Host=db)
      - ConnectionStrings__DefaultConnection=Host=db;Database=reservas_db;Username=admin;Password=password123
      #Configuración de autoridad JWT apuntando al contenedor de Keycloak
      - Jwt__Authority=http://keycloak:8080/realms/RestaurantesRealm
      - Jwt__Audience=account
      - ConnectionStrings__RedisConnection=redis:6379
    depends_on:
      - db
      - keycloak
      - mongo-router
    networks:
      - restaurante_net

# CLÚSTER MONGODB ------------------------------------------ 
# Config server
# El servidor de configuración guarda los metadatos y el mapa del sharding
  mongo-config:
    image: mongo:7.0
    container_name: mongo_config
    command: mongod --configsvr --replSet configRS --port 27019 --bind_ip_all
    ports:
      - "27019:27019"
    volumes:
      - mongo_config_data:/data/configdb
    networks:
      - restaurante_net

# Shard (replica set)
# Nodo 1 (Primario)
  mongo-shard-1a:
    image: mongo:7.0
    container_name: mongo_shard_1a
    # El comando --shardsvr le dice que es un trabajador de almacenamiento
    command: mongod --shardsvr --replSet shard1RS --port 27018 --bind_ip_all
    ports:
      - "27118:27018"
    volumes:
      - mongo_shard_1a_data:/data/db
    networks:
      - restaurante_net

  # Nodo 2 (Secundario)
  mongo-shard-1b:
    image: mongo:7.0
    container_name: mongo_shard_1b
    command: mongod --shardsvr --replSet shard1RS --port 27018 --bind_ip_all
    ports:
      - "27218:27018"
    volumes:
      - mongo_shard_1b_data:/data/db
    networks:
      - restaurante_net

  # Nodo 3 (Secundario)
  mongo-shard-1c:
    image: mongo:7.0
    container_name: mongo_shard_1c
    command: mongod --shardsvr --replSet shard1RS --port 27018 --bind_ip_all
    ports:
      - "27318:27018"
    volumes:
      - mongo_shard_1c_data:/data/db
    networks:
      - restaurante_net

# Router (mongos)
  mongo-router:
    image: mongo:7.0
    container_name: mongo_router
    # Aquí le decimos al recepcionista dónde está el directorio (Config Server)
    command: mongos --configdb configRS/mongo-config:27019 --bind_ip_all
    ports:
      - "27017:27017" # El puerto estándar de Mongo, para que la API se conecte fácil
    networks:
      - restaurante_net
    depends_on:
      - mongo-config
      - mongo-shard-1a
      - mongo-shard-1b
      - mongo-shard-1c

# Balanceador de carga (Nginx)
  nginx:
    image: nginx:latest
    container_name: balanceador_restaurante
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    networks:
      - restaurante_net
  
#VOLÚMENES: Garantizan la persistencia de datos tras el reinicio de los contenedores
volumes:
  base_datos_nueva:
  keycloak_data:
  mongo_config_data:
  mongo_shard_1a_data:
  mongo_shard_1b_data:
  mongo_shard_1c_data:

networks:
  restaurante_net:
    driver: bridge