# Este archivo se encarga de levantar toda la infraestructura del sistema
# por medio de Docker Compose.
#
# Aquí se definen todos los servicios que necesita la aplicación para funcionar:
# PostgreSQL como base de datos relacional principal, Keycloak para manejar la
# autenticación y los roles, Redis como caché, MongoDB configurado como clúster
# con sharding, Elasticsearch para búsquedas, la API desarrollada en .NET y Nginx
# como balanceador de carga.
#
# La idea de este archivo es poder ejecutar el sistema completo en un ambiente
# local de forma ordenada, sin tener que configurar cada servicio manualmente.
# Cada contenedor se comunica con los demás por medio de la red interna
# restaurante_net, lo que permite que la API pueda conectarse a servicios como
# PostgreSQL, Redis, MongoDB, Keycloak y Elasticsearch usando los nombres de los
# servicios como si fueran direcciones internas.
#
# También se definen volúmenes para conservar la información aunque los
# contenedores se detengan o se reinicien. Esto es importante para no perder los
# datos de PostgreSQL, MongoDB, Keycloak y Elasticsearch durante las pruebas del
# proyecto.

version: '3.8'

services:
  db:
    image: postgres:16
    container_name: base_datos_restaurante
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: reservas_db
      
    ports:
      - "5432:5432"
    volumes:
      - base_datos_nueva:/var/lib/postgresql/data
    networks:
      - restaurante_net

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: auth_restaurante
    command: start-dev --import-realm 
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak_data:/opt/keycloak/data
      - ./keycloak_import:/opt/keycloak/data/import 
    networks:
      - restaurante_net

  redis:
    image: redis:latest
    container_name: cache_restaurante
    ports:
      - "6379:6379"
    networks:
      - restaurante_net

  api:
    build:
      context: ./RestauranteApi 
      dockerfile: Dockerfile
    #container_name: api_restaurante
    deploy:
      replicas: 3
    #ports:
      #- "5085:8080" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseEngine=Postgres
      - ConnectionStrings__MongoConnection=mongodb://mongo-router:27017
      - ConnectionStrings__DefaultConnection=Host=db;Database=reservas_db;Username=admin;Password=password123
      - Jwt__Authority=http://keycloak:8080/realms/RestaurantesRealm
      - Jwt__Audience=account
      - ConnectionStrings__RedisConnection=redis:6379
      - ConnectionStrings__ElasticConnection=http://elasticsearch:9200
    depends_on:
      - db
      - keycloak
      - mongo-router
      - elasticsearch
    networks:
      - restaurante_net

  mongo-config:
    image: mongo:7.0
    container_name: mongo_config
    command: mongod --configsvr --replSet configRS --port 27019 --bind_ip_all
    ports:
      - "27019:27019"
    volumes:
      - mongo_config_data:/data/configdb
    networks:
      - restaurante_net

  mongo-shard-1a:
    image: mongo:7.0
    container_name: mongo_shard_1a
    command: mongod --shardsvr --replSet shard1RS --port 27018 --bind_ip_all
    ports:
      - "27118:27018"
    volumes:
      - mongo_shard_1a_data:/data/db
    networks:
      - restaurante_net

  mongo-shard-1b:
    image: mongo:7.0
    container_name: mongo_shard_1b
    command: mongod --shardsvr --replSet shard1RS --port 27018 --bind_ip_all
    ports:
      - "27218:27018"
    volumes:
      - mongo_shard_1b_data:/data/db
    networks:
      - restaurante_net

  mongo-shard-1c:
    image: mongo:7.0
    container_name: mongo_shard_1c
    command: mongod --shardsvr --replSet shard1RS --port 27018 --bind_ip_all
    ports:
      - "27318:27018"
    volumes:
      - mongo_shard_1c_data:/data/db
    networks:
      - restaurante_net

  mongo-router:
    image: mongo:7.0
    container_name: mongo_router
    command: mongos --configdb configRS/mongo-config:27019 --bind_ip_all
    ports:
      - "27017:27017"
    networks:
      - restaurante_net
    depends_on:
      - mongo-config
      - mongo-shard-1a
      - mongo-shard-1b
      - mongo-shard-1c

  nginx:
    image: nginx:latest
    container_name: balanceador_restaurante
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    networks:
      - restaurante_net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: buscador_restaurante
    environment:
      - discovery.type=single-node 
      - xpack.security.enabled=false 
      - ES_JAVA_OPTS=-Xms512m -Xmx512m 
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - restaurante_net

volumes:
  base_datos_nueva:
  keycloak_data:
  mongo_config_data:
  mongo_shard_1a_data:
  mongo_shard_1b_data:
  mongo_shard_1c_data:
  elasticsearch_data:

networks:
  restaurante_net:
    driver: bridge