# Este archivo configura Nginx como balanceador de carga y proxy inverso
# para la API del sistema.
#
# Su función principal es recibir las solicitudes HTTP que llegan al puerto 80
# y redirigirlas hacia la API que se ejecuta dentro de los contenedores de Docker.
# De esta forma, Nginx funciona como el punto de entrada del sistema y ayuda a
# organizar el tráfico que llega desde el exterior.
#
# También se definen rutas específicas para separar mejor las solicitudes. Por
# ejemplo, las peticiones que llegan a /api/ se envían a la API principal, las de
# /swagger/ permiten acceder a la documentación de los endpoints, y las de
# /search/ se usan para las funciones relacionadas con búsqueda.
#
# Además, se agregan encabezados como Host y X-Real-IP para que la API pueda
# recibir información del cliente original que hizo la solicitud.

events { worker_connections 1024; }

http {
    upstream api_servers {
        server api:8080; 
    }

    server {
        listen 80;

        location /api/ {
            proxy_pass http://api:8080; 
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /swagger/ {
            proxy_pass http://api_servers/swagger/;
        }

        location /search/ {
            proxy_pass http://api_servers/search/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}