from __future__ import annotations

import csv
from pathlib import Path
from typing import Any


ROOT_DIR = Path(__file__).resolve().parents[1]
RAW_DATA_DIR = ROOT_DIR / "spark" / "data" / "raw_data"


def write_csv(
    filename: str,
    fieldnames: list[str],
    rows: list[dict[str, Any]],
) -> None:
    """Write deterministic UTF-8 CSV data to the shared raw-data folder."""
    RAW_DATA_DIR.mkdir(parents=True, exist_ok=True)
    output_path = RAW_DATA_DIR / filename

    with output_path.open(
        mode="w",
        newline="",
        encoding="utf-8-sig",
    ) as csv_file:
        writer = csv.DictWriter(csv_file, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    print(f"{filename}: {len(rows)} registros generados")


locations = [
    {
        "id": 1,
        "name": "Cartago Centro",
        "province": "Cartago",
        "canton": "Cartago",
        "district": "Oriental",
        "latitude": 9.8644,
        "longitude": -83.9194,
        "location_type": "restaurant",
    },
    {
        "id": 2,
        "name": "San Pedro Centro",
        "province": "San José",
        "canton": "Montes de Oca",
        "district": "San Pedro",
        "latitude": 9.9281,
        "longitude": -84.0507,
        "location_type": "restaurant",
    },
    {
        "id": 3,
        "name": "Heredia Centro",
        "province": "Heredia",
        "canton": "Heredia",
        "district": "Heredia",
        "latitude": 9.9980,
        "longitude": -84.1165,
        "location_type": "restaurant",
    },
    {
        "id": 4,
        "name": "Alajuela Centro",
        "province": "Alajuela",
        "canton": "Alajuela",
        "district": "Alajuela",
        "latitude": 10.0163,
        "longitude": -84.2116,
        "location_type": "restaurant",
    },
    {
        "id": 5,
        "name": "Escazú Centro",
        "province": "San José",
        "canton": "Escazú",
        "district": "Escazú",
        "latitude": 9.9197,
        "longitude": -84.1398,
        "location_type": "restaurant",
    },
    {
        "id": 101,
        "name": "Tres Ríos",
        "province": "Cartago",
        "canton": "La Unión",
        "district": "Tres Ríos",
        "latitude": 9.9064,
        "longitude": -83.9876,
        "location_type": "customer",
    },
    {
        "id": 102,
        "name": "Curridabat Centro",
        "province": "San José",
        "canton": "Curridabat",
        "district": "Curridabat",
        "latitude": 9.9118,
        "longitude": -84.0341,
        "location_type": "customer",
    },
    {
        "id": 103,
        "name": "Guadalupe Centro",
        "province": "San José",
        "canton": "Goicoechea",
        "district": "Guadalupe",
        "latitude": 9.9466,
        "longitude": -84.0556,
        "location_type": "customer",
    },
    {
        "id": 104,
        "name": "Sabanilla",
        "province": "San José",
        "canton": "Montes de Oca",
        "district": "Sabanilla",
        "latitude": 9.9450,
        "longitude": -84.0390,
        "location_type": "customer",
    },
    {
        "id": 105,
        "name": "San Rafael de Heredia",
        "province": "Heredia",
        "canton": "San Rafael",
        "district": "San Rafael",
        "latitude": 10.0135,
        "longitude": -84.1001,
        "location_type": "customer",
    },
    {
        "id": 106,
        "name": "Belén",
        "province": "Heredia",
        "canton": "Belén",
        "district": "San Antonio",
        "latitude": 9.9795,
        "longitude": -84.1882,
        "location_type": "customer",
    },
    {
        "id": 107,
        "name": "Desamparados Centro",
        "province": "San José",
        "canton": "Desamparados",
        "district": "Desamparados",
        "latitude": 9.8967,
        "longitude": -84.0627,
        "location_type": "customer",
    },
    {
        "id": 108,
        "name": "Paraíso Centro",
        "province": "Cartago",
        "canton": "Paraíso",
        "district": "Paraíso",
        "latitude": 9.8383,
        "longitude": -83.8656,
        "location_type": "customer",
    },
    {
        "id": 109,
        "name": "El Tejar",
        "province": "Cartago",
        "canton": "El Guarco",
        "district": "El Tejar",
        "latitude": 9.8479,
        "longitude": -83.9391,
        "location_type": "customer",
    },
    {
        "id": 110,
        "name": "Moravia Centro",
        "province": "San José",
        "canton": "Moravia",
        "district": "San Vicente",
        "latitude": 9.9616,
        "longitude": -84.0474,
        "location_type": "customer",
    },
    {
        "id": 111,
        "name": "San Ramón Centro",
        "province": "Alajuela",
        "canton": "San Ramón",
        "district": "San Ramón",
        "latitude": 10.0872,
        "longitude": -84.4702,
        "location_type": "customer",
    },
    {
        "id": 112,
        "name": "Grecia Centro",
        "province": "Alajuela",
        "canton": "Grecia",
        "district": "Grecia",
        "latitude": 10.0730,
        "longitude": -84.3127,
        "location_type": "customer",
    },
    {
        "id": 113,
        "name": "La Sabana",
        "province": "San José",
        "canton": "San José",
        "district": "Mata Redonda",
        "latitude": 9.9350,
        "longitude": -84.1088,
        "location_type": "customer",
    },
    {
        "id": 114,
        "name": "Santa Ana Centro",
        "province": "San José",
        "canton": "Santa Ana",
        "district": "Santa Ana",
        "latitude": 9.9326,
        "longitude": -84.1827,
        "location_type": "customer",
    },
    {
        "id": 115,
        "name": "San Pablo de Heredia",
        "province": "Heredia",
        "canton": "San Pablo",
        "district": "San Pablo",
        "latitude": 9.9957,
        "longitude": -84.0966,
        "location_type": "customer",
    },
]

users = [
    {
        "id": 1,
        "keycloak_id": "kc-user-001",
        "name": "Ana Rodríguez",
        "email": "ana.rodriguez@example.com",
        "role": "cliente",
        "location_id": 101,
    },
    {
        "id": 2,
        "keycloak_id": "kc-user-002",
        "name": "Carlos Méndez",
        "email": "carlos.mendez@example.com",
        "role": "cliente",
        "location_id": 102,
    },
    {
        "id": 3,
        "keycloak_id": "kc-user-003",
        "name": "María Vargas",
        "email": "maria.vargas@example.com",
        "role": "cliente",
        "location_id": 103,
    },
    {
        "id": 4,
        "keycloak_id": "kc-user-004",
        "name": "José Ramírez",
        "email": "jose.ramirez@example.com",
        "role": "cliente",
        "location_id": 104,
    },
    {
        "id": 5,
        "keycloak_id": "kc-user-005",
        "name": "Lucía Fernández",
        "email": "lucia.fernandez@example.com",
        "role": "cliente",
        "location_id": 105,
    },
    {
        "id": 6,
        "keycloak_id": "kc-user-006",
        "name": "Andrés Soto",
        "email": "andres.soto@example.com",
        "role": "cliente",
        "location_id": 106,
    },
    {
        "id": 7,
        "keycloak_id": "kc-user-007",
        "name": "Sofía Jiménez",
        "email": "sofia.jimenez@example.com",
        "role": "cliente",
        "location_id": 107,
    },
    {
        "id": 8,
        "keycloak_id": "kc-user-008",
        "name": "Diego Mora",
        "email": "diego.mora@example.com",
        "role": "cliente",
        "location_id": 108,
    },
    {
        "id": 9,
        "keycloak_id": "kc-user-009",
        "name": "Valentina Castro",
        "email": "valentina.castro@example.com",
        "role": "cliente",
        "location_id": 109,
    },
    {
        "id": 10,
        "keycloak_id": "kc-user-010",
        "name": "Daniel Herrera",
        "email": "daniel.herrera@example.com",
        "role": "cliente",
        "location_id": 110,
    },
    {
        "id": 11,
        "keycloak_id": "kc-user-011",
        "name": "Gabriela Rojas",
        "email": "gabriela.rojas@example.com",
        "role": "cliente",
        "location_id": 111,
    },
    {
        "id": 12,
        "keycloak_id": "kc-user-012",
        "name": "Sebastián Arias",
        "email": "sebastian.arias@example.com",
        "role": "cliente",
        "location_id": 112,
    },
    {
        "id": 13,
        "keycloak_id": "kc-user-013",
        "name": "Camila Salas",
        "email": "camila.salas@example.com",
        "role": "cliente",
        "location_id": 113,
    },
    {
        "id": 14,
        "keycloak_id": "kc-user-014",
        "name": "Mateo Quesada",
        "email": "mateo.quesada@example.com",
        "role": "cliente",
        "location_id": 114,
    },
    {
        "id": 15,
        "keycloak_id": "kc-user-015",
        "name": "Natalia Villalobos",
        "email": "natalia.villalobos@example.com",
        "role": "cliente",
        "location_id": 115,
    },
]

restaurants = [
    {
        "id": 1,
        "name": "Sabores de Cartago",
        "address": "Avenida 2, Cartago Centro",
        "phone": "2551-1001",
        "location_id": 1,
    },
    {
        "id": 2,
        "name": "Urbano Bistro",
        "address": "San Pedro, Montes de Oca",
        "phone": "2280-2002",
        "location_id": 2,
    },
    {
        "id": 3,
        "name": "Café Herediano",
        "address": "Heredia Centro",
        "phone": "2260-3003",
        "location_id": 3,
    },
    {
        "id": 4,
        "name": "Sazón Alajuelense",
        "address": "Alajuela Centro",
        "phone": "2430-4004",
        "location_id": 4,
    },
    {
        "id": 5,
        "name": "Terraza Escazú",
        "address": "Escazú Centro",
        "phone": "2228-5005",
        "location_id": 5,
    },
]

menus = [
    {
        "id": 1,
        "name": "Casado tradicional",
        "description": "Arroz, frijoles, ensalada, plátano y proteína",
        "price": 4500,
        "category": "Platos fuertes",
        "restaurant_id": 1,
    },
    {
        "id": 2,
        "name": "Olla de carne",
        "description": "Sopa tradicional con carne y vegetales",
        "price": 5200,
        "category": "Sopas",
        "restaurant_id": 1,
    },
    {
        "id": 3,
        "name": "Chifrijo",
        "description": "Arroz, frijoles, chicharrón y pico de gallo",
        "price": 3800,
        "category": "Entradas",
        "restaurant_id": 1,
    },
    {
        "id": 4,
        "name": "Refresco natural",
        "description": "Bebida de fruta de temporada",
        "price": 1500,
        "category": "Bebidas",
        "restaurant_id": 1,
    },
    {
        "id": 5,
        "name": "Arroz con pollo",
        "description": "Arroz con pollo, ensalada y papas",
        "price": 4200,
        "category": "Platos fuertes",
        "restaurant_id": 1,
    },
    {
        "id": 6,
        "name": "Tres leches",
        "description": "Postre tradicional de tres leches",
        "price": 2300,
        "category": "Postres",
        "restaurant_id": 1,
    },
    {
        "id": 7,
        "name": "Hamburguesa urbana",
        "description": "Carne, queso, vegetales y salsa de la casa",
        "price": 5600,
        "category": "Comida rápida",
        "restaurant_id": 2,
    },
    {
        "id": 8,
        "name": "Papas rústicas",
        "description": "Papas horneadas con especias y salsa",
        "price": 2200,
        "category": "Acompañamientos",
        "restaurant_id": 2,
    },
    {
        "id": 9,
        "name": "Pizza margarita",
        "description": "Salsa de tomate, mozzarella y albahaca",
        "price": 6200,
        "category": "Pizzas",
        "restaurant_id": 2,
    },
    {
        "id": 10,
        "name": "Limonada con hierbabuena",
        "description": "Bebida natural con limón y hierbabuena",
        "price": 1800,
        "category": "Bebidas",
        "restaurant_id": 2,
    },
    {
        "id": 11,
        "name": "Wrap de pollo",
        "description": "Tortilla con pollo, vegetales y aderezo",
        "price": 4600,
        "category": "Comida rápida",
        "restaurant_id": 2,
    },
    {
        "id": 12,
        "name": "Brownie con helado",
        "description": "Brownie de chocolate con helado de vainilla",
        "price": 2900,
        "category": "Postres",
        "restaurant_id": 2,
    },
    {
        "id": 13,
        "name": "Café chorreado",
        "description": "Café costarricense preparado al momento",
        "price": 1400,
        "category": "Bebidas",
        "restaurant_id": 3,
    },
    {
        "id": 14,
        "name": "Cheesecake de café",
        "description": "Postre cremoso elaborado con café",
        "price": 2800,
        "category": "Postres",
        "restaurant_id": 3,
    },
    {
        "id": 15,
        "name": "Sándwich herediano",
        "description": "Pan artesanal con jamón, queso y vegetales",
        "price": 4200,
        "category": "Sándwiches",
        "restaurant_id": 3,
    },
    {
        "id": 16,
        "name": "Gallo pinto especial",
        "description": "Gallo pinto con huevo, queso y natilla",
        "price": 3500,
        "category": "Desayunos",
        "restaurant_id": 3,
    },
    {
        "id": 17,
        "name": "Capuchino",
        "description": "Café espresso con leche espumada",
        "price": 2100,
        "category": "Bebidas",
        "restaurant_id": 3,
    },
    {
        "id": 18,
        "name": "Queque de zanahoria",
        "description": "Queque artesanal con cobertura cremosa",
        "price": 2500,
        "category": "Postres",
        "restaurant_id": 3,
    },
    {
        "id": 19,
        "name": "Pollo a la plancha",
        "description": "Pechuga de pollo con vegetales y arroz",
        "price": 4900,
        "category": "Platos fuertes",
        "restaurant_id": 4,
    },
    {
        "id": 20,
        "name": "Tacos alajuelenses",
        "description": "Tacos de carne con repollo y salsa",
        "price": 3600,
        "category": "Comida rápida",
        "restaurant_id": 4,
    },
    {
        "id": 21,
        "name": "Sopa negra",
        "description": "Sopa de frijoles negros con huevo",
        "price": 3200,
        "category": "Sopas",
        "restaurant_id": 4,
    },
    {
        "id": 22,
        "name": "Batido de mora",
        "description": "Batido natural de mora",
        "price": 1900,
        "category": "Bebidas",
        "restaurant_id": 4,
    },
    {
        "id": 23,
        "name": "Empanada arreglada",
        "description": "Empanada con carne, repollo y salsas",
        "price": 2400,
        "category": "Entradas",
        "restaurant_id": 4,
    },
    {
        "id": 24,
        "name": "Flan de coco",
        "description": "Flan artesanal de coco",
        "price": 2300,
        "category": "Postres",
        "restaurant_id": 4,
    },
    {
        "id": 25,
        "name": "Salmón a la parrilla",
        "description": "Salmón con vegetales y puré",
        "price": 8200,
        "category": "Platos fuertes",
        "restaurant_id": 5,
    },
    {
        "id": 26,
        "name": "Pasta Alfredo",
        "description": "Pasta con salsa Alfredo y pollo",
        "price": 6500,
        "category": "Pastas",
        "restaurant_id": 5,
    },
    {
        "id": 27,
        "name": "Ensalada mediterránea",
        "description": "Lechuga, tomate, aceitunas y queso",
        "price": 4800,
        "category": "Ensaladas",
        "restaurant_id": 5,
    },
    {
        "id": 28,
        "name": "Bruschetta",
        "description": "Pan tostado con tomate y albahaca",
        "price": 3300,
        "category": "Entradas",
        "restaurant_id": 5,
    },
    {
        "id": 29,
        "name": "Té frío de frutos rojos",
        "description": "Té frío natural con frutos rojos",
        "price": 2100,
        "category": "Bebidas",
        "restaurant_id": 5,
    },
    {
        "id": 30,
        "name": "Volcán de chocolate",
        "description": "Pastel de chocolate con centro líquido",
        "price": 3400,
        "category": "Postres",
        "restaurant_id": 5,
    },
]


def main() -> None:
    write_csv(
        "locations.csv",
        [
            "id",
            "name",
            "province",
            "canton",
            "district",
            "latitude",
            "longitude",
            "location_type",
        ],
        locations,
    )

    write_csv(
        "users.csv",
        [
            "id",
            "keycloak_id",
            "name",
            "email",
            "role",
            "location_id",
        ],
        users,
    )

    write_csv(
        "restaurants.csv",
        [
            "id",
            "name",
            "address",
            "phone",
            "location_id",
        ],
        restaurants,
    )

    write_csv(
        "menus.csv",
        [
            "id",
            "name",
            "description",
            "price",
            "category",
            "restaurant_id",
        ],
        menus,
    )

    print(f"Datos maestros guardados en: {RAW_DATA_DIR}")


if __name__ == "__main__":
    main()